### ISSUE TITLE
could made it print the dynamic html content?

### ISSUE THREAD

**Issue by focus0802** [crabbly/Print.js#5] opened 2016-09-13 09:43 UTC
I'm using Vue.js:

`
    <div id="print-area">
    <img v-bind:src="currentInvoice.image">
    </div>
`
this above code will dynamically generate a img into #print-area.
and i use the function printJS('print-area','html'), it's not working, just a blank page unless refresh the page.
so, coulid it print the content dynamically like printJS($('#print-area'),'html').

**Comment by crabbly** [comment] 2016-09-13 16:43
@FOCUSWEB The library should support dynamic content without a problem. I'll run some tests and try to replicate this issue. 
What browser are you using? Have you tried different browsers?

**Comment by FOCUSWEB** [comment] 2016-09-14 03:57
Google chrome
I tried printJS({{currentInvoice.image}},'image') with no problem.
I think it generate the iframe code at initialization, so it can't be dynamically print the html content.

**Comment by crabbly** [comment] 2017-03-06 18:14
@focus0802 , Sorry I haven't got back to you on this. The iframe is created on the fly, for each print.  It should work just fine with Vue.js. Where you able to make this work?

**Comment by melturphin** [comment] 2017-03-28 12:51
the same happens to me. I'm using  http://interactjs.io/

**Comment by melturphin** [comment] 2017-04-01 07:31
the problem is when **transform** is used.

**Comment by crabbly** [comment] 2017-04-01 16:34
@melturphin Thank you for pointing this out. I'll take a look at it as soon as I can.

**Comment by TakesTheBiscuit** [comment] 2017-11-01 10:28
I'm struggling here with Angular 1.6.x to print anything dynamic, not sure what i'm doing wrong but the print preview window comes up blank, nothing like what's on the page

**Comment by TakesTheBiscuit** [comment] 2017-11-01 10:40
I've ended up doing window.print() until i can find a work around with print.js printJS

**Comment by crabbly** [comment] 2017-11-01 14:37
I have been using the library to print dynamically created elements without any issues. 
Are you passing the `html` parameter?

I created a fiddle to show an example, please take a look.
http://jsfiddle.net/crabbly/uck6ur3z/

This example uses Vuejs to render a list of html printable areas from an array of javascript objects. These objects could come from an api through an AJAX call. 

If you post some code here, I may be able to help identify the issue.

**Comment by TakesTheBiscuit** [comment] 2017-11-01 14:43
@crabbly thanks for taking a look -- i will try my best to simplify my issue, i tried putting an ID on the whole body element and targeting that with:
```
<body id="something">
</body>

printJS('something', 'html');
```

But that didn't do it, so an interesting one, i've read your comments about dynamically created iFrame, i haven't looked at how your lib works but i expected it to in effect copy the live-contents of all the divs into an iframe and then issue print() against that ? In which case i wonder if angular is struggling to render inside the iframe

**Comment by crabbly** [comment] 2017-11-01 14:52
The library will gather the html from the element you pass in, and structure it inside the iframe. Then print that iframe. 

Shouldn't be a problem adding an id to the body to print it, however, that's not something I will even test, because if you are printing the whole body, you don't even need the library at all, just use `window.print()` like you mentioned.

Depending how your code is, you may have to wait for angular to render all elements before trying to print. Either way, as long as the elements are already rendered, they should print without issues.

**Comment by TakesTheBiscuit** [comment] 2017-11-01 14:55
Hi thanks for filling in the blanks -- i totally agree with you re: body, it was a stupid workaround i was trying (my own debugging if you will), i tried on a container div and had no luck so thought i would jump the the highest level of DOM element i could which is body right? 

There's definitely an issue here, i'm going to try and find a spare few mins to rip some code out of this project for you/us to look at -- perhaps it is trivial but i feel like there is some sort of angular/printJS conflict.

Just as an aside, is there a recommended way to debug why the output would be blank? I have _OK_ JS skills.

**Comment by crabbly** [comment] 2017-11-01 14:59
Cool. Yea, if you post some code or create a fiddle I may be able to help more. I'll leave this issue open for now.

Check you console for any errors. Also, using dev tools, take a look at your html elements. The lib will leave the used `iframe` element at the end of your `body`, untill is re-used. Of course it is hidden, but you can change that, and take a look inside that iframe body. Check if the wanted "printable" html has been created there.

**Comment by TakesTheBiscuit** [comment] 2017-11-01 15:12
Hey @crabbly there is a chance this is css or something.

Screenshots, i know it's not 'code' yet but you'll see the iframe has the right content but Chrome does not.

Chrome Version 61.0.3163.100 (Official Build) (64-bit)
on
macOS 10.12.1 (16B2555)

'left over iframe':
<img width="453" alt="screen shot 2017-11-01 at 15 10 34" src="https://user-images.githubusercontent.com/15122732/32281522-f8313a78-bf16-11e7-948a-2dca91859406.png">

chrome print preview:
<img width="1086" alt="screen shot 2017-11-01 at 15 08 29" src="https://user-images.githubusercontent.com/15122732/32281523-f846db12-bf16-11e7-8ecd-d9ac77179578.png">

**Comment by crabbly** [comment] 2017-11-01 15:34
This is weird. After the lib creates the iframe, all it does form there is print. So, as long as you can see it in the iframe, it should print. I think you are right, it must be a css issue. Even because the print document shows 2 pages, something is being passed to the printer, but somehow is blank.

Do you have any css print media queries?

**Comment by TakesTheBiscuit** [comment] 2017-11-01 16:07
Got it!

If you check my iframe's html (rendered) content it contains both angular tags (`ng-show`) and a class of 'ng-hide' and a million inline style parts.

<img width="534" alt="screen shot 2017-11-01 at 16 02 02" src="https://user-images.githubusercontent.com/15122732/32284168-430155d6-bf1e-11e7-9e79-aa45ed9b6f1f.png">

I have no idea if this is normal behaviour right now, but i do have quite a lot of nested divs. Perhaps my markup is a bit heavy for printJS at the moment?

```
<div class="panel panel-default" style="border-bottom-color:rgb(221, 221, 221);border-bottom-left-radius:4px;border-bottom-right-radius:4px;border-bottom-style:solid;border-bottom-width:0.989583px;border-collapse:separate;border-image-outset:0px;border-image-repeat:stretch;border-image-slice:100%;border-image-source:none;border-image-width:1;border-left-color:rgb(221, 221, 221);border-left-style:solid;border-left-width:0.989583px;border-right-color:rgb(221, 221, 221);border-right-style:solid;border-right-width:0.989583px;border-top-color:rgb(221, 221, 221);border-top-left-radius:4px;border-top-right-radius:4px;border-top-style:solid;border-top-width:0.989583px;box-shadow:rgba(0, 0, 0, 0.05) 0px 1px 1px 0px;box-sizing:border-box;break-after:auto;break-before:auto;break-inside:auto;clear:none;display:block;float:none;height:auto;margin-bottom:20px;margin-left:0px;margin-right:0px;margin-top:0px;max-height:none;min-height:0px;min-width:0px;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0px;text-decoration:none solid rgb(51, 51, 51);text-decoration-line:none;text-decoration-style:solid;text-decoration-color:rgb(51, 51, 51);text-decoration-skip:objects;width:auto;word-break:normal;-webkit-border-horizontal-spacing:0px;-webkit-border-image:none;-webkit-border-vertical-spacing:0px;-webkit-box-align:stretch;-webkit-box-decoration-break:slice;-webkit-box-decoration-break:slice;-webkit-box-direction:normal;-webkit-box-flex:0;-webkit-box-flex-group:1;-webkit-box-lines:single;-webkit-box-ordinal-group:1;-webkit-box-orient:horizontal;-webkit-box-pack:start;-webkit-box-reflect:none;-webkit-line-break:auto;-webkit-margin-before-collapse:collapse;-webkit-margin-after-collapse:collapse;-webkit-mask-box-image:none;-webkit-mask-box-image-outset:0px;-webkit-mask-box-image-repeat:stretch;-webkit-mask-box-image-slice:0 fill;-webkit-mask-box-image-source:none;-webkit-mask-box-image-width:auto;shape-margin:0px;-webkit-text-decorations-in-effect:none;line-break:auto;max-width: 800px !important;12pt !important;">
                <div class="panel-heading" style="border-bottom-color:rgb(221, 221, 221);border-bottom-left-radius:0px;border-bottom-right-radius:0px;border-bottom-style:solid;border-bottom-width:0.989583px;border-collapse:separate;border-image-outset:0px;border-image-repeat:stretch;border-image-slice:100%;border-image-source:none;border-image-width:1;border-left-color:rgb(221, 221, 221);border-left-style:none;border-left-width:0px;border-right-color:rgb(221, 221, 221);border-right-style:none;border-right-width:0px;border-top-color:rgb(221, 221, 221);border-top-left-radius:3px;border-top-right-radius:3px;border-top-style:none;border-top-width:0px;box-shadow:none;box-sizing:border-box;break-after:auto;break-before:auto;break-inside:auto;clear:none;display:block;float:none;height:auto;margin-bottom:0px;margin-left:0px;margin-right:0px;margin-top:0px;max-height:none;min-height:0px;min-width:0px;padding-bottom:10px;padding-left:15px;padding-right:15px;padding-top:10px;text-decoration:none solid rgb(51, 51, 51);text-decoration-line:none;text-decoration-style:solid;text-decoration-color:rgb(51, 51, 51);text-decoration-skip:objects;width:auto;word-break:normal;-webkit-border-horizontal-spacing:0px;-webkit-border-image:none;-webkit-border-vertical-spacing:0px;-webkit-box-align:stretch;-webkit-box-decoration-break:slice;-webkit-box-decoration-break:slice;-webkit-box-direction:normal;-webkit-box-flex:0;-webkit-box-flex-group:1;-webkit-box-lines:single;-webkit-box-ordinal-group:1;-webkit-box-orient:horizontal;-webkit-box-pack:start;-webkit-box-reflect:none;-webkit-line-break:auto;-webkit-margin-before-collapse:collapse;-webkit-margin-after-collapse:collapse;-webkit-mask-box-image:none;-webkit-mask-box-image-outset:0px;-webkit-mask-box-image-repeat:stretch;-webkit-mask-box-image-slice:0 fill;-webkit-mask-box-image-source:none;-webkit-mask-box-image-width:auto;shape-margin:0px;-webkit-text-decorations-in-effect:none;line-break:auto;max-width: 800px !important;12pt !important;">
                	<span style="border-bottom-color:rgb(51, 51, 51);border-bottom-left-radius:0px;border-bottom-right-radius:0px;border-bottom-style:none;border-bottom-width:0px;border-collapse:separate;border-image-outset:0px;border-image-repeat:stretch;border-image-slice:100%;border-image-source:none;border-image-width:1;border-left-color:rgb(51, 51, 51);border-left-style:none;border-left-width:0px;border-right-color:rgb(51, 51, 51);border-right-style:none;border-right-width:0px;border-top-color:rgb(51, 51, 51);border-top-left-radius:0px;border-top-right-radius:0px;border-top-style:none;border-top-width:0px;box-shadow:none;box-sizing:border-box;break-after:auto;break-before:auto;break-inside:auto;clear:none;display:inline;float:none;height:auto;margin-bottom:0px;margin-left:0px;margin-right:0px;margin-top:0px;max-height:none;min-height:0px;min-width:0px;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0px;text-decoration:none solid rgb(51, 51, 51);text-decoration-line:none;text-decoration-style:solid;text-decoration-color:rgb(51, 51, 51);text-decoration-skip:objects;width:auto;word-break:normal;-webkit-border-horizontal-spacing:0px;-webkit-border-image:none;-webkit-border-vertical-spacing:0px;-webkit-box-align:stretch;-webkit-box-decoration-break:slice;-webkit-box-decoration-break:slice;-webkit-box-direction:normal;-webkit-box-flex:0;-webkit-box-flex-group:1;-webkit-box-lines:single;-webkit-box-ordinal-group:1;-webkit-box-orient:horizontal;-webkit-box-pack:start;-webkit-box-reflect:none;-webkit-line-break:auto;-webkit-margin-before-collapse:collapse;-webkit-margin-after-collapse:collapse;-webkit-mask-box-image:none;-webkit-mask-box-image-outset:0px;-webkit-mask-box-image-repeat:stretch;-webkit-mask-box-image-slice:0 fill;-webkit-mask-box-image-source:none;-webkit-mask-box-image-width:auto;shape-margin:0px;-webkit-text-decorations-in-effect:none;line-break:auto;max-width: 800px !important;12pt !important;"><i class="fa fa-list" aria-hidden="true" style="border-bottom-color:rgb(51, 51, 51);border-bottom-left-radius:0px;border-bottom-right-radius:0px;border-bottom-style:none;border-bottom-width:0px;border-collapse:separate;border-image-outset:0px;border-image-repeat:stretch;border-image-slice:100%;border-image-source:none;border-image-width:1;border-left-color:rgb(51, 51, 51);border-left-style:none;border-left-width:0px;border-right-color:rgb(51, 51, 51);border-right-style:none;border-right-width:0px;border-top-color:rgb(51, 51, 51);border-top-left-radius:0px;border-top-right-radius:0px;border-top-style:none;border-top-width:0px;box-shadow:none;box-sizing:border-box;break-after:auto;break-before:auto;break-inside:auto;clear:none;display:inline-block;float:none;height:auto;margin-bottom:0px;margin-left:0px;margin-right:0px;margin-top:0px;max-height:none;min-height:0px;min-width:0px;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0px;text-decoration:none solid rgb(51, 51, 51);text-decoration-line:none;text-decoration-style:solid;text-decoration-color:rgb(51, 51, 51);text-decoration-skip:objects;width:auto;word-break:normal;-webkit-border-horizontal-spacing:0px;-webkit-border-image:none;-webkit-border-vertical-spacing:0px;-webkit-box-align:stretch;-webkit-box-decoration-break:slice;-webkit-box-decoration-break:slice;-webkit-box-direction:normal;-webkit-box-flex:0;-webkit-box-flex-group:1;-webkit-box-lines:single;-webkit-box-ordinal-group:1;-webkit-box-orient:horizontal;-webkit-box-pack:start;-webkit-box-reflect:none;-webkit-line-break:auto;-webkit-margin-before-collapse:collapse;-webkit-margin-after-collapse:collapse;-webkit-mask-box-image:none;-webkit-mask-box-image-outset:0px;-webkit-mask-box-image-repeat:stretch;-webkit-mask-box-image-slice:0 fill;-webkit-mask-box-image-source:none;-webkit-mask-box-image-width:auto;shape-margin:0px;-webkit-text-decorations-in-effect:none;line-break:auto;max-width: 800px !important;12pt !important;"></i> &nbsp;Order #127</span>
                	<a class="btn btn-primary btn-sm btn-xs pull-right" href="http://kiosk.app/order" style="border-bottom-color:rgb(46, 109, 164);border-bottom-left-radius:3px;border-bottom-right-radius:3px;border-bottom-style:solid;border-bottom-width:0.989583px;border-collapse:separate;border-image-outset:0px;border-image-repeat:stretch;border-image-slice:100%;border-image-source:none;border-image-width:1;border-left-color:rgb(46, 109, 164);border-left-style:solid;border-left-width:0.989583px;border-right-color:rgb(46, 109, 164);border-right-style:solid;border-right-width:0.989583px;border-top-color:rgb(46, 109, 164);border-top-left-radius:3px;border-top-right-radius:3px;border-top-style:solid;border-top-width:0.989583px;box-shadow:none;box-sizing:border-box;break-after:auto;break-before:auto;break-inside:auto;clear:none;display:block;float:right;height:auto;margin-bottom:0px;margin-left:0px;margin-right:0px;margin-top:0px;max-height:none;min-height:0px;min-width:0px;padding-bottom:1px;padding-left:5px;padding-right:5px;padding-top:1px;text-decoration:none solid rgb(255, 255, 255);text-decoration-line:none;text-decoration-style:solid;text-decoration-color:rgb(255, 255, 255);text-decoration-skip:objects;width:auto;word-break:normal;-webkit-border-horizontal-spacing:0px;-webkit-border-image:none;-webkit-border-vertical-spacing:0px;-webkit-box-align:stretch;-webkit-box-decoration-break:slice;-webkit-box-decoration-break:slice;-webkit-box-direction:normal;-webkit-box-flex:0;-webkit-box-flex-group:1;-webkit-box-lines:single;-webkit-box-ordinal-group:1;-webkit-box-orient:horizontal;-webkit-box-pack:start;-webkit-box-reflect:none;-webkit-line-break:auto;-webkit-margin-before-collapse:collapse;-webkit-margin-after-collapse:collapse;-webkit-mask-box-image:none;-webkit-mask-box-image-outset:0px;-webkit-mask-box-image-repeat:stretch;-webkit-mask-box-image-slice:0 fill;-webkit-mask-box-image-source:none;-webkit-mask-box-image-width:auto;shape-margin:0px;-webkit-text-decorations-in-effect:none;line-break:auto;max-width: 800px !important;12pt !important;"><i class="fa fa-list" aria-hidden="true" style="border-bottom-color:rgb(255, 255, 255);border-bottom-left-radius:0px;border-bottom-right-radius:0px;border-bottom-style:none;border-bottom-width:0px;border-collapse:separate;border-image-outset:0px;border-image-repeat:stretch;border-image-slice:100%;border-image-source:none;border-image-width:1;border-left-color:rgb(255, 255, 255);border-left-style:none;border-left-width:0px;border-right-color:rgb(255, 255, 255);border-right-style:none;border-right-width:0px;border-top-color:rgb(255, 255, 255);border-top-left-radius:0px;border-top-right-radius:0px;border-top-style:none;border-top-width:0px;box-shadow:none;box-sizing:border-box;break-after:auto;break-before:auto;break-inside:auto;clear:none;display:inline-block;float:none;height:auto;margin-bottom:0px;margin-left:0px;margin-right:0px;margin-top:0px;max-height:none;min-height:0px;min-width:0px;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0px;text-decoration:none solid rgb(255, 255, 255);text-decoration-line:none;text-decoration-style:solid;text-decoration-color:rgb(255, 255, 255);text-decoration-skip:objects;width:auto;word-break:normal;-webkit-border-horizontal-spacing:0px;-webkit-border-image:none;-webkit-border-vertical-spacing:0px;-webkit-box-align:stretch;-webkit-box-decoration-break:slice;-webkit-box-decoration-break:slice;-webkit-box-direction:normal;-webkit-box-flex:0;-webkit-box-flex-group:1;-webkit-box-lines:single;-webkit-box-ordinal-group:1;-webkit-box-orient:horizontal;-webkit-box-pack:start;-webkit-box-reflect:none;-webkit-line-break:auto;-webkit-margin-before-collapse:collapse;-webkit-margin-after-collapse:collapse;-webkit-mask-box-image:none;-webkit-mask-box-image-outset:0px;-webkit-mask-box-image-repeat:stretch;-webkit-mask-box-image-slice:0 fill;-webkit-mask-box-image-source:none;-webkit-mask-box-image-width:auto;shape-margin:0px;-webkit-text-decorations-in-effect:none;line-break:auto;max-width: 800px !important;12pt !important;"></i> &nbsp;back</a>
                    <div class="pull-right" style="border-bottom-color:rgb(51, 51, 51);border-bottom-left-radius:0px;border-bottom-right-radius:0px;border-bottom-style:none;border-bottom-width:0px;border-collapse:separate;border-image-outset:0px;border-image-repeat:stretch;border-image-slice:100%;border-image-source:none;border-image-width:1;border-left-color:rgb(51, 51, 51);border-left-style:none;border-left-width:0px;border-right-color:rgb(51, 51, 51);border-right-style:none;border-right-width:0px;border-top-color:rgb(51, 51, 51);border-top-left-radius:0px;border-top-right-radius:0px;border-top-style:none;border-top-width:0px;box-shadow:none;box-sizing:border-box;break-after:auto;break-before:auto;break-inside:auto;clear:none;display:block;float:right;height:auto;margin-bottom:0px;margin-left:0px;margin-right:0px;margin-top:0px;max-height:none;min-height:0px;min-width:0px;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0px;text-decoration:none solid rgb(51, 51, 51);text-decoration-line:none;text-decoration-style:solid;text-decoration-color:rgb(51, 51, 51);text-decoration-skip:objects;width:auto;word-break:normal;-webkit-border-horizontal-spacing:0px;-webkit-border-image:none;-webkit-border-vertical-spacing:0px;-webkit-box-align:stretch;-webkit-box-decoration-break:slice;-webkit-box-decoration-break:slice;-webkit-box-direction:normal;-webkit-box-flex:0;-webkit-box-flex-group:1;-webkit-box-lines:single;-webkit-box-ordinal-group:1;-webkit-box-orient:horizontal;-webkit-box-pack:start;-webkit-box-reflect:none;-webkit-line-break:auto;-webkit-margin-before-collapse:collapse;-webkit-margin-after-collapse:collapse;-webkit-mask-box-image:none;-webkit-mask-box-image-outset:0px;-webkit-mask-box-image-repeat:stretch;-webkit-mask-box-image-slice:0 fill;-webkit-mask-box-image-source:none;-webkit-mask-box-image-width:auto;shape-margin:0px;-webkit-text-decorations-in-effect:none;line-break:auto;max-width: 800px !important;12pt !important;">
```

**Comment by crabbly** [comment] 2017-11-01 16:12
All the inline style is the expected behavior. 
It shouldn't matter how heavy the markup is. Unless you got a console error confirming a possible crash. 

I'm wondering if the `ng-show` and `ng-hide` could have anything to do with this issue. 

Could you remove them and run a quick test?

**Comment by crabbly** [comment] 2017-11-03 14:41
@TakesTheBiscuit Where you able to test this without `ng-show` and `ng-hide`?

**Comment by crabbly** [comment] 2017-11-04 17:43
I'll close this issue since I don't believe it is directly related to the library. 
As we can see in the fiddle posted above, it prints dynamic html content without issues.
Please open it again if you have more information that we could work with. 
Thank you.

**Closed by crabbly** 2017-11-04 17:43 UTC
