### ISSUE TITLE
Select option not printing

### ISSUE THREAD

**Issue by shakeelsadiq** [crabbly/Print.js#186] opened 2018-06-29 09:46 UTC
I am printing a html form which has textboxes, datepickers, dropdowns etc.  I'm finding that the dropdown does not show the selected value but instead shows 'Please Select'.  I'm not sure if this is due to PrintJs or if it is a more general reason.

**Comment by crabbly** [comment] 2018-06-29 15:13
Hey @shakeelsadiq , thank you for pointing this out. 
Looks like this issue is related to the library. When we copy the html to an iframe in order to print, the dropdown select data isn't transferred. 

Here is a fiddle for test purposes:
https://jsfiddle.net/crabbly/uf5nw233/

We will have to add extra logic to the html processing in order to fix this.

**Comment by crabbly** [comment] 2018-07-24 02:23
The problem is due to the use of cloneNode in html.js. https://github.com/crabbly/Print.js/blob/master/src/js/html.js#L18
We will need to change this logic. 

I'll close this issue in favor of #187 to prevent duplication, since they are the same.
Thank you.

**Closed by crabbly** 2018-07-24 02:23 UTC

**Comment by crabbly** [comment] 2019-05-27 03:55
Checkbox state is now supported by the library.
Please run `npm update print-js` to get the latest version.

Feel free to reopen this if any issues. Thank you.
