### ISSUE TITLE
Printing html content in an electron application is incomplete

### ISSUE THREAD

**Issue by shunchenghe01** [crabbly/Print.js#255] opened 2018-11-16 04:21 UTC
The printed content is blank in the second page of the electron application. I put the generated frame in a normal html page and call document.getElementById("printJS").contentWindow.print() to print the second page.

**Comment by crabbly** [comment] 2018-11-21 16:33
Hi @shunchenghe01, I never used the library in an electron app. However, if you were able to print with the `.print()` command, the library should work as well, since it uses the same thing.

What are you trying to print? PDF, HTML...

**Comment by shunchenghe01** [comment] 2018-11-22 01:31
@crabbly Thank you for your answer. I found that there was no such problem after I lowered the electron version to 2.x. In the process of using print-js, I found that the 'printable' parameter must be the id attribute of the dom element. If I want to centralize the content of multiple scattered doms together, it is very difficult to use print-js. I have an idea, if the parameter 'printable' can directly pass a dom element object or an array of dom elements or the id attribute of the dom element, it can solve the problem that the contents of multiple doms cannot be printed together. Or you can provide an extra property, I pass the rendered html text directly, call the print-js interface to print the content

**Comment by shunchenghe01** [comment] 2018-11-22 01:37
@crabbly The 'type' attribute adds several values such as html-dom, html-text, html-url. When I call the print method in 'html.js', I get the element to be printed according to the type.

**Comment by popod** [comment] 2018-12-14 17:03
Hi,

This is a known bug with Electron 3 : electron/electron#14260. Only the first page is printed with macOS. Works fine on Windows.

**Comment by crabbly** [comment] 2018-12-14 21:55
Hey @shunchenghe01, I'm not sure I understand the concept of multiple doms. However, about passing raw html, it may be something we could add. Not a lot of value, since we could just render that HTML first, hidden, and print that. Rendering may be interesting when the HTML template has images. Either way, a PR would be welcome.

@popod Thank you for the information. I will go ahead and close this issue since the problem is related to electron. 

Feel free to reopen this if there is anything we could do here to improve the lib. Thx again.

**Closed by crabbly** 2018-12-14 21:55 UTC
