### ISSUE TITLE
can't load properly a PDF on Safari browsers

### ISSUE THREAD

**Issue by xtornasol512** [crabbly/Print.js#111] opened 2018-01-03 23:27 UTC
When load a PDF on chrome show correct and properly the PDF, but in Safari cut a little the header, so the pdf is not show properly.
This is the PDF header rendered on chrome
<img width="820" alt="screen shot 2018-01-03 at 5 23 49 pm" src="https://user-images.githubusercontent.com/1806894/34544259-ed274422-f0aa-11e7-8ef2-1bb129bb8fdb.png" title="pdf on chrome">
This is the PDF header rendered on safari
<img width="923" alt="screen shot 2018-01-03 at 5 23 12 pm" src="https://user-images.githubusercontent.com/1806894/34544272-004319dc-f0ab-11e7-84d4-996d5a651b32.png" title="pdf on safari">
Both are same PDF and with other pdf is the same problem. If there is any idea why and what's happend!? please let me know!

**Comment by crabbly** [comment] 2018-01-08 16:58
@xtornasol512 Hey Jesús, I just tested and confirmed the behavior. Looks like there is a margin issue when printing PDF files using Safari. I'm not sure why this is happening. Will try to find a solution for it.

**Comment by crabbly** [comment] 2018-02-09 15:36
@xtornasol512 Looks like Safari is printing pdf's properly now. Could you give it a try from the documentation page? It uses the latest package version.
http://printjs.crabbly.com/

Also, my Safari version is 11.0.2. If you are still having issues, please try to update your browser first. Let me know how it goes. Thx.

**Comment by xtornasol512** [comment] 2018-02-14 19:59
Still have this problem, first try with just update safari browser to 11.0.3 Nothing change.
Then update the printJS files printjs.min.js and printjs.css.min
But I still have the problem with the margins on pdf on safari
<img width="236" alt="screen shot 2018-02-14 at 1 30 10 pm" src="https://user-images.githubusercontent.com/1806894/36224057-039a8050-118c-11e8-8310-4fdfcb5296ef.png">

![issue_printjs](https://user-images.githubusercontent.com/1806894/36225079-2e0eee40-118f-11e8-887e-2f673ff56eb3.png)

**Comment by jboor-mdsol** [comment] 2018-05-22 06:32
+1
Also dynamically added content like watermarks or texts are missing in print window in Safari. Can you please look at it?

**Comment by xtornasol512** [comment] 2018-09-10 23:42
Hey, has been pass so much time! But now we have updated our PDF, and adjust the margins manually and almost resolve the problem.
However the problem also appear when print the pdf physically, some printers didn't give us the pdf with the proper margins and cut it. So thats why we adjust the margins and fix the problem on printers, we try on again with PrintJS and now there is only a little margin that cut but the PDF is printed on good conditions. 
<img width="1196" alt="screen shot 2018-09-10 at 6 15 10 pm" src="https://user-images.githubusercontent.com/1806894/45330079-44f51880-b529-11e8-9478-95d93130e780.png">

**Comment by crabbly** [comment] 2018-09-13 15:27
Looks like Safari is still not processing margins correctly. I'm not sure how to fix this.

**Comment by xtornasol512** [comment] 2018-09-13 17:26
Sure, no problem @crabbly, but for the moment I recommend to others to adjust his pdf with proper margins. I'm not justifying Safari to do that, but remains us to adjust the margin for printers!

**Comment by crabbly** [comment] 2019-05-20 19:48
Closing this in favor of #33. Keeping all browser compatibility issues under that ticket.

**Closed** 2019-05-20 19:48 UTC
Labels: help wanted
