### ISSUE TITLE
Please give a full example on how to import and USE this with angular 2

### ISSUE THREAD

**Issue by oomz** [crabbly/Print.js#121] opened 2018-01-31 09:45 UTC
I am able to install it, am not sure if i am importing it correctly but it does not throw any errors, but when i try to use it, it gives me an error: 'TypeError: _co.printJS is not a function'. So how to use this library properly? newbie here

**Comment by crabbly** [comment] 2018-01-31 16:35
Hey @oomz , the usage is the same independent of which framework you use.
First, make sure the package is installed: `npm install print-js --save`.
Then import into your project: `import printJS from 'print-js';`

The library assigns the global variable `printJS`, which can be used anywhere in the project.

For example: `printJS('my_pdf.pdf')`

If you need more help, please post some of your code here.

**Comment by crabbly** [comment] 2018-02-02 20:31
@oomz Since you didn't post any code here, I'll close this. Feel free to add some code and reopen if necessary.

**Closed by crabbly** 2018-02-02 20:31 UTC

**Comment by subatomicglue** [comment] 2018-08-16 19:08
Just following the above instruction
```
npm install print-js --save.

Then import into your project: 
import printJS from 'print-js'
```
I've added `import printJS from 'print-js'` both to top of my component needing `printJS`, or to the `app.module.ts` file WITHOUT adding to `imports` or `declarations`, since both places create an error.   I also tried adding to the `typings.d.ts` file as `declare var printJS: any;`

```
Error Message: "_co.printJS is not a function"
In Component: MyComponent
In Element: app-my-component

Stack:
TypeError: _co.printJS is not a function
at Object.eval [as handleEvent] (ng:///AppModule/MyComponent.ngfactory.js:71:31)
at handleEvent (webpack-internal:///./node_modules/@angular/core/esm5/core.js:13747:155)
at callWithDebugContext (webpack-internal:///./node_modules/@angular/core/esm5/core.js:15256:42)
at Object.debugHandleEvent [as handleEvent] (webpack-internal:///./node_modules/@angular/core/esm5/core.js:14843:12)
at dispatchEvent (webpack-internal:///./node_modules/@angular/core/esm5/core.js:10159:25)
at eval (webpack-internal:///./node_modules/@angular/core/esm5/core.js:10784:38)
at HTMLDivElement.eval (webpack-internal:///./node_modules/@angular/platform-browser/esm5/platform-browser.js:2680:53)
at ZoneDelegate.invokeTask (webpack-internal:///./node_modules/zone.js/dist/zone.js:421:31)
at Object.onInvokeTask (webpack-internal:///./node_modules/@angular/core/esm5/core.js:4939:33)
at ZoneDelegate.invokeTask (webpack-internal:///./node_modules/zone.js/dist/zone.js:420:36)
```

**Comment by crabbly** [comment] 2018-08-16 19:59
There is not special step about importing this library when using angular. Just import it like any other package.
However, if you import the lib inside the same file you are writing your code (same scope), using `import printJS from 'print-js'` is a problem since the variable `printJS` will be overwriten. 
Try using `import print from 'print-js'` instead.

**Comment by subatomicglue** [comment] 2018-08-16 20:40
Yep, my mis-read of the above instructions.  It totally works.  

Wonder if the import syntax should be listed on http://printjs.crabbly.com/#documentation so people dont have to come looking in the issue section here.  If nothing else, than to reassure them it works well / tested in angular2+, etc..

**Comment by crabbly** [comment] 2018-08-16 20:42
Agree. 
I just added to the README page. Will add to the documentation page as well.

**Comment by crabbly** [comment] 2018-09-22 05:11
Just published a new version to npm which has proper support for module import.
The library will still expose a global variable `printJS`, but the recommend usage now should be to import the package at the same file where it will be used:

For ex.:

`import printJS from 'print-js'`

`printJS('path-to.pdf')`

Run `npm update print-js` to get the latest version.

**Comment by PavelShvykyj** [comment] 2018-10-02 10:08
Hi. Using Angular5 and  print-js 1.0.52. 
I try to
 `import printJS from "print-js"`
 and then
 `printJS({printable :'myId',  type : 'html'});`
  as resoult :  
> ERROR TypeError: print_js_1.default is not a function.

 where do i make a mistake?  Thank you.

**Comment by crabbly** [comment] 2018-10-11 17:40
Hi @PavelShvykyj , 

This should work. Here is a CodeSandbox showing the import and usage in a generic javascript project:
https://codesandbox.io/s/x2yrj0kwww

It should work the same way when using Angular. However, feel free to replicate the issue in a new CodeSandBox and I'll look into it. Thanks.

**Comment by PavelShvykyj** [comment] 2018-10-12 06:42
Thanks for your reply. The code really works fine for JS. Obviously problem is in the my wrong use it for the type script. I will add a comment if I can find a solution. Thanks again.

**Comment by fabiothz** [comment] 2018-10-12 13:46
> Hi. Using Angular5 and print-js 1.0.52.
> I try to
> `import printJS from "print-js"`
> and then
> `printJS({printable :'myId', type : 'html'});`
> as resoult :
> 
> > ERROR TypeError: print_js_1.default is not a function.
> 
> where do i make a mistake? Thank you.

I'm also having this problem!
My version of Angular and PrintJS is the same.

However, the production version is working ...

**Comment by fabiothz** [comment] 2018-10-12 14:33
I just solved it by importing like this:
`import printJS from 'print-js/src/index';`

Can there be any problem importing like this?

**Comment by PavelShvykyj** [comment] 2018-10-12 15:23
Yes, the problem was solved with this import. Thank you very much, fabiothz!!!

**Comment by kamal0912** [comment] 2018-11-30 10:45
> Using `Angular5` and latest `print-js`
> 
> Just following the above instruction
> 
> ```
> npm install print-js --save.
> 
> Then import into your project: 
> import printJS from 'print-js'
> ```
> Since it's ambiguous what `import into your project` means, I tried `import printJS from 'print-js'` both to top of my `component.ts` file, or to the `app.module.ts` file (WITHOUT adding anything to `imports` or `declarations`, since both places create an error). I also tried adding to the `typings.d.ts` file as `declare var printJS: any;`
> 
> ```
> Error Message: "_co.printJS is not a function"
> In Component: MyComponent
> In Element: app-my-component
> 
> Stack:
> TypeError: _co.printJS is not a function
> at Object.eval [as handleEvent] (ng:///AppModule/MyComponent.ngfactory.js:71:31)
> at handleEvent (webpack-internal:///./node_modules/@angular/core/esm5/core.js:13747:155)
> at callWithDebugContext (webpack-internal:///./node_modules/@angular/core/esm5/core.js:15256:42)
> at Object.debugHandleEvent [as handleEvent] (webpack-internal:///./node_modules/@angular/core/esm5/core.js:14843:12)
> at dispatchEvent (webpack-internal:///./node_modules/@angular/core/esm5/core.js:10159:25)
> at eval (webpack-internal:///./node_modules/@angular/core/esm5/core.js:10784:38)
> at HTMLDivElement.eval (webpack-internal:///./node_modules/@angular/platform-browser/esm5/platform-browser.js:2680:53)
> at ZoneDelegate.invokeTask (webpack-internal:///./node_modules/zone.js/dist/zone.js:421:31)
> at Object.onInvokeTask (webpack-internal:///./node_modules/@angular/core/esm5/core.js:4939:33)
> at ZoneDelegate.invokeTask (webpack-internal:///./node_modules/zone.js/dist/zone.js:420:36)
> ```

@subatomicglue I am getting this same issue in Angular 4. Can you please tell me the steps to resolve?

**Comment by onedotover** [comment] 2018-12-15 02:16
On Angular 6 and the print-js 1.0.54 I still had to use
`import printJS from 'print-js/src/index';`
to get around
`ERROR TypeError: print_js_1.default is not a function.`

**Comment by sezmars** [comment] 2018-12-24 16:03
@onedotover, @kamal0912, @fabiothz, @PavelShvykyj, @subatomicglue, @oomz

`export * from 'print-js';`  ||  `export * from 'print-js/src/index';`

**Comment by sudharsan203** [comment] 2019-03-26 04:58
@sezmars will you please put the code here

**Comment by asfernandes** [comment] 2019-04-01 17:49
I'm trying with `import printJS from 'print-js';` with 1.0.55 and TypeScript with Webpack and having the error `print_js_1.default is not a function`.

It works for me with `const printJS = require('print-js');` but then I lost the type info. It's declared as `any`.

**Comment by crabbly** [comment] 2019-04-01 18:24
Hey @asfernandes,
Where is it declared as `any`? 

I thought it was being declared as a function here:
https://github.com/crabbly/Print.js/blob/master/index.d.ts#L36-L37

**Comment by asfernandes** [comment] 2019-04-01 18:36
When I `import` it, the type is peeked but at runtime does not work.

When I `require` it the type is not peek (normal, TypeScript does not use type with `require`) and works at runtime.

**Comment by crabbly** [comment] 2019-04-01 18:54
I haven't yet used Typescript. Therefore, I'm not too familiar with it. 
Could you take a look at the library interface and check if there is anything we could do to fix this?
I thought this problem was fixed already. :/
https://github.com/crabbly/Print.js/blob/master/index.d.ts

**Comment by asfernandes** [comment] 2019-04-01 19:41
Maybe as that https://stackoverflow.com/questions/39109027/write-a-declaration-file-for-a-default-export-module ?

**Comment by sezmars** [comment] 2019-04-01 23:37
> @sezmars will you please put the code here

What you meen? I threw an example.

After many studies, I would not recommend this method, it distorts the image and the quality is very low.

I can advise another library, from which I received excellent results

**Comment by asfernandes** [comment] 2019-04-02 11:35
I've added crabbly/Print.js#293

**Comment by stathoula** [comment] 2019-05-29 12:33
import printJS from 'print-js', wasn't working for me.

import * as printJS from 'print-js', worked for me :)

**Comment by asfernandes** [comment] 2019-05-29 13:28
> import printJS from 'print-js', wasn't working for me.
> 

The correct is `import printJS = require('print-js');`

**Comment by crabbly** [comment] 2019-05-29 13:29
@stathoula 
Thank you, Efstathia.

I updated the condesandbox below and confirmed that this works:
https://codesandbox.io/s/wq7pplxznl

I hope we can update the interface to just use `import printJS from 'print-js'`

**Comment by crabbly** [comment] 2019-05-29 13:34
@asfernandes
Hey Adriano, using require does indeed work. The codesandbox has that as an example in there as well.

I think lots of people, if not most, are trying to use es6 module imports instead. That's what I prefer these days. 

Any ideas what we could do on the interface to support that?
Thank you.

**Comment by crabbly** [comment] 2019-05-29 17:43
Thank you, @asfernandes. The package is exported using default here: https://github.com/crabbly/Print.js/blob/master/src/index.js#L10

However, the interface doesn't have a default export. 
Do you know if we could accomplish that? Like adding `export default printJS` to `index.d.ts`.

**Comment by asfernandes** [comment] 2019-05-29 18:06
@crabbly the interface seems to not be a problem. Could you please generate an dist non-minified print.js so I can see it? The one currently generated is identical to print.min.js so it's difficult to understand.
