### ISSUE TITLE
Option documentTitle is not working

### ISSUE THREAD

**Issue by singgihmardianto** [crabbly/Print.js#362] opened 2019-08-15 13:13 UTC
Hello, 

seems that documentTitle option isn't working.

This is my jsfiddle: https://jsfiddle.net/xnp5aht2/

Thank you

**Comment by JandersonConstantino** [comment] 2019-08-22 23:19
Hi, what's your browser?
Your example works for me on Chrome browser.
![image](https://user-images.githubusercontent.com/15123834/63556149-214c9780-c51a-11e9-8692-6ca8d0b9fba4.png)

**Comment by singgihmardianto** [comment] 2019-08-23 03:43
This is my browser version. 

<img width="705" alt="Screen Shot 2019-08-23 at 10 30 12" src="https://user-images.githubusercontent.com/5870490/63564972-62cc5980-c591-11e9-9d4b-1a561923a82d.png">

As the documentation said that documentTitle is:
> When printing html, image or json, this will be shown as the document title. It will also be the name of the document, if the user tries to save the print job to a pdf file.

And what happen to me is the documentTitle is not working as the name of the document when I tried to save to print.

**Comment by JandersonConstantino** [comment] 2019-08-23 10:46
Ok, now I understand, thanks.

**Comment by amrita-syn** [comment] 2019-08-28 10:57
Facing the same issue. Any update to this please?

**Comment by eljefedelrodeodeljefe** [comment] 2019-10-31 17:37
I traced it down. I think the issue is appending the the iframe to body (in the raw-html case at least). The properties are correctly set and I even override them explicitly again. The only change that worked was setting document.title .... which overrides the title of the calling page though.

**Comment by crabbly** [comment] 2019-11-15 03:24
Hey guys, sorry for the delay on this. I just tried the fiddle using Chrome 78 on a mac and it works. Are you still having issues?

**Comment by crabbly** [comment] 2019-11-19 03:13
@JandersonConstantino @eljefedelrodeodeljefe @singgihmardianto
Whenever you have a chance, could you please confirm that this issue is still happening with Chrome 78? It's working for me right now.
Thank you.

**Comment by amrita-syn** [comment] 2019-11-19 09:11
> @JandersonConstantino @eljefedelrodeodeljefe @singgihmardianto
> Whenever you have a chance, could you please confirm that this issue is still happening with Chrome 78? It's working for me right now.
> Thank you.

The issue is still happening. The jsfiddle shared in the question - when opened in chrome 78 shows the original window title.
![image](https://user-images.githubusercontent.com/45505551/69132737-a83deb80-0ada-11ea-99e0-b7fe1193ace3.png)

**Comment by singgihmardianto** [comment] 2019-11-24 14:04
Thank you @amrita-syn, same here with me still not working. But if you guys need quick solution, you can use @eljefedelrodeodeljefe solution, it works for me.

**Comment by fd6130** [comment] 2020-02-12 07:56
It seems the issue still there. `documentTitle` isn't working.

**Comment by amrita-syn** [comment] 2020-02-12 10:05
If it helps, I ended up with the following - using the onPrintDialogClose. Partial satisfaction; when you focus back on the browser window/tab, you have your title back.

`function printToPdf(content, filename) {`
`    document.getElementsByTagName('body')[0].append(content);`
`    const div = document.getElementById('pdf-content');`
`    document.title = filename.trim().replaceAll(' ', '-');`
`    print({ printable: 'pdf-content',`
`                    type: 'html',`
`                    documentTitle: filename,`
`                    onPrintDialogClose: () => document.title = 'Original Title'`
`                });`
`    div.remove();`
`}`

![image](https://user-images.githubusercontent.com/45505551/74324493-2265cf80-4dad-11ea-8ece-ef3adeee27ab.png)

**Comment by JandersonConstantino** [comment] 2020-02-15 21:09
yes, I didn't find another way to fix this.
I will go to propose a correction, but I don't believe this will be accepted.

**Comment by MaikkiaM** [comment] 2020-05-03 13:13
After try different things, i cannot change the DocumentTitle for a download.
What am I doing wrong?
![image](https://user-images.githubusercontent.com/37313886/80915159-a6967600-8d50-11ea-8b53-c64c92b596c3.png)
![image](https://user-images.githubusercontent.com/37313886/80915161-aac29380-8d50-11ea-95a1-abf8ac161114.png)

**Comment by crabbly** [comment] 2020-10-07 02:11
Hey guys, the purpose of the `documentTitle` is to customize the browser injected title or header into the print result. So far, this seems to be working as expected.

Here is the fiddle updated with a custom title:
https://jsfiddle.net/crabbly/zvo7fsc4/

And below is the screen shot of the print preview:
<img width="789" alt="printjs-documentTitle" src="https://user-images.githubusercontent.com/16927940/95279053-afb7d180-081f-11eb-8d14-04f19c4f3069.png">

If the user user's browser offers an option to save the print job as a PDF, that's a different feature. We will have to tweak the library to support that. Even though is a bit outside of the library scope, which focus on printing, not PDF generation or downloads. I hope we can get this done. PRs are welcomed! :)

I'll close this issue since we already have another thread focusing on this: #487 

Thank you.

**Closed by crabbly** 2020-10-07 02:11 UTC

**Comment by davidsavoie1** [comment] 2022-07-22 16:04
I know this is a closed topic, but I want to share my own very simple workaround to ensure the downloadable printed pdf filename  respects the title. Basically, I save a reference to the current document title before calling `printpdf`, then I restore the old `document.title` with a very small delay. Somehow, it seems to be working very well both on Chrome and Firefox.

```js
function print() {
  const currTitle = document.title;
  document.title = "My PDF title";

  printjs("id", "html");

  setTimeout(() => (document.title = currTitle), 300);
}
```

**Comment by AlinaaMoskalenko** [comment] 2022-08-04 18:54
The problem also can be with the pdf file. Your PDF file must have a title. Your can check with Adobe Acrobat (Select File -> Properties).
