### ISSUE TITLE
Not working in Safari

### ISSUE THREAD

**Issue by johngarcia9110** [crabbly/Print.js#238] opened 2018-09-30 02:52 UTC
**When attempting to print inside safari I get the following error:**

TypeError: undefined is not an object (evaluating 't.indexOf')

**Here are my settings:**

```
printJS({
        printable: 'resultsTable',
        type: 'html',
        showModal : true ,
       });
```

**Additional info:**

- I am loading Print.js via the cdn
- The modal opens successfully, then hangs until I get the error message (above)

**Comment by crabbly** [comment] 2018-09-30 16:58
Hi @johngarcia9110 , thanks for reporting this issue. I just confirmed the issue. Looks like its happening with Safari only. I'll try to figure out a solution for it.

**Comment by crabbly** [comment] 2018-10-19 18:41
The new version is now available in npm, which has the fix for this. 
Just run `npm update print-js` to get it.
Thanks.

**Closed by crabbly** 2018-10-19 18:41 UTC
